### ISSUE TITLE
page tree internationalization meta.json order => makes previous page / next page dissapear

### ISSUE THREAD

**Issue by apescasio** [fuma-nama/fumadocs#2602]
### To Reproduce

1. Using the examples i18n 
2. I create a folder called git in content/docs
3. I do index.mdx + index.cn.mdx and test.mdx + test.cn.mdx 
4. A meta.json file with pages for the 2 docs
5. I create another folder called bash in content/docs
6. I do index.mdx etc 
7. A meta.json file with pages for the 2 docs
8. Open localhost => goto the other language thats not default (vice versa) => the previous page + next page dissapears.

### Current vs. Expected behavior

previous page + next page should not be dissapearing

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32494
  Available CPU cores: 16
Binaries:
  Node: 24.8.0
  npm: 11.6.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 16.0.1 // Latest available version is detected (16.0.1).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Examples

**Comment by pjborowiecki** [comment]
I am experiencing a similar issue. There is a strange flash when switching locale, and a dysfunctional selection dropdown appears in the top left corner. 

Everythin worked perfectly fine, but the issue started happening when I updated from `"next": "^15.6.0-canary.19"`, to `"next": "^16.0.1"`. Looks like there is some incompatibility there, not sure whether it should be fixed in fumadocs or in next. Everything still working fine when updating fumadocs packages to their latest versions (    `"fumadocs-core": "^16.0.8"`, `"fumadocs-mdx": "^13.0.5"`, `"fumadocs-ui": "^16.0.8"`), and keeping next at `canary.19`.

https://github.com/user-attachments/assets/b762fa66-cb18-499a-aab3-1a9c3bdf4afe

**Comment by fuma-nama** [comment]
I think it’s another problem related to stylesheet/layout remounting in Next.js, need a separate reproduction to look into.

**Comment by fuma-nama** [comment]
confirmed the original issue, fix will be released this week

**Comment by pjborowiecki** [comment]
Thank you @fuma-nama :) I can confirm it's fixed and working perfectly fine

**Comment by apescasio** [comment]
> Thank you [@fuma-nama](https://github.com/fuma-nama) :) I can confirm it's fixed and working perfectly fine

Hi, can you please share me your repo with the working package.json ? I thought that I could get the fix by doing "npm create fumadocs-app" and then simply getting the package.json values from it like     "fumadocs-core": "16.0.10", and applying it to my current project but it still did not fix the dissapearing previous page / next page. I'd like to see your solution.

**Comment by fuma-nama** [comment]
It's 16.0.11, your package manager may have cached the CLI package somehow, try `create fumadocs-core@latest`
